# Generated by Django 5.2.17 on 2026-09-02 05:04

import apps.common.uuid7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0002_booking_bookingsegment_inventoryhold_passenger_and_more'),
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketSerial',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('airline_prefix', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('last_serial', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, unique=True)),
                ('ticket_number', models.CharField(max_length=13, unique=True)),
                ('issued_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('ISSUED', 'Issued'), ('EXCHANGED', 'Exchanged'), ('REFUNDED', 'Refunded'), ('VOID', 'Void')], default='ISSUED', max_length=12)),
                ('fare_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('fare_calculation', models.TextField(blank=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='booking.booking')),
                ('conjunction_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conjunctions', to='ticketing.ticket')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_issued', to=settings.AUTH_USER_MODEL)),
                ('issuing_airline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='catalog.airline')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='booking.passenger')),
            ],
            options={
                'ordering': ['ticket_number'],
            },
        ),
        migrations.CreateModel(
            name='TicketCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coupon_number', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('OPEN', 'Open for use'), ('CHECKED_IN', 'Checked in'), ('LIFTED', 'Lifted'), ('FLOWN', 'Flown'), ('EXCHANGED', 'Exchanged'), ('REFUNDED', 'Refunded'), ('VOID', 'Void')], default='OPEN', max_length=12)),
                ('flown_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('exchanged_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchanged_from', to='ticketing.ticketcoupon')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coupons', to='booking.bookingsegment')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='ticketing.ticket')),
            ],
            options={
                'ordering': ['coupon_number'],
            },
        ),
        migrations.CreateModel(
            name='TicketEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('ISSUED', 'Issued'), ('VOIDED', 'Voided'), ('EXCHANGED', 'Exchanged'), ('REFUNDED', 'Refunded'), ('COUPON_USED', 'Coupon used')], max_length=16)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_events', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='ticketing.ticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['booking'], name='idx_ticket_booking'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ISSUED')), fields=('booking', 'passenger'), name='uniq_live_ticket_per_passenger'),
        ),
        migrations.AddConstraint(
            model_name='ticketcoupon',
            constraint=models.UniqueConstraint(fields=('ticket', 'coupon_number'), name='uniq_coupon_number'),
        ),
        migrations.AddIndex(
            model_name='ticketevent',
            index=models.Index(fields=['ticket', 'created_at'], name='idx_ticket_event'),
        ),
    ]
