# Generated by Django 5.2.17 on 2026-09-02 06:28

import apps.common.uuid7
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_price_breakdown'),
        ('inventory', '0001_initial'),
        ('ops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disruption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, unique=True)),
                ('type', models.CharField(choices=[('CANCELLATION', 'Cancellation'), ('DELAY', 'Significant delay'), ('DIVERSION', 'Diversion'), ('SCHEDULE_CHANGE', 'Schedule change')], max_length=20)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('delay_minutes', models.IntegerField(default=0)),
                ('detected_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disruptions', to='inventory.flight')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='RebookOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, unique=True)),
                ('cabin', models.CharField(max_length=16)),
                ('rbd', models.CharField(max_length=1)),
                ('fare_delta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('rank', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('OFFERED', 'Offered'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired')], default='OFFERED', max_length=10)),
                ('expires_at', models.DateTimeField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rebook_options', to='booking.booking')),
                ('disruption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='ops.disruption')),
                ('proposed_flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rebook_options', to='inventory.flight')),
            ],
            options={
                'ordering': ['rank', 'proposed_flight__departure_utc'],
            },
        ),
        migrations.AddIndex(
            model_name='disruption',
            index=models.Index(fields=['-detected_at'], name='idx_disruption_recent'),
        ),
        migrations.AddIndex(
            model_name='disruption',
            index=models.Index(condition=models.Q(('resolved_at__isnull', True)), fields=['flight'], name='idx_disruption_open'),
        ),
        migrations.AddConstraint(
            model_name='disruption',
            constraint=models.UniqueConstraint(condition=models.Q(('resolved_at__isnull', True)), fields=('flight', 'type'), name='uniq_open_disruption'),
        ),
        migrations.AddIndex(
            model_name='rebookoption',
            index=models.Index(fields=['booking', 'status'], name='idx_option_booking'),
        ),
        migrations.AddConstraint(
            model_name='rebookoption',
            constraint=models.UniqueConstraint(fields=('booking', 'proposed_flight'), name='uniq_option_per_flight'),
        ),
    ]
