# Generated by Django 5.2.17 on 2026-09-02 05:04

import apps.common.uuid7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0002_booking_bookingsegment_inventoryhold_passenger_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, unique=True)),
                ('provider', models.CharField(max_length=32)),
                ('provider_intent_id', models.CharField(max_length=128, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('REQUIRES_PAYMENT', 'Requires payment method'), ('REQUIRES_ACTION', 'Requires customer action (3DS)'), ('PROCESSING', 'Processing'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='REQUIRES_PAYMENT', max_length=20)),
                ('client_secret', models.CharField(max_length=128)),
                ('capture_method', models.CharField(choices=[('AUTOMATIC', 'Automatic'), ('MANUAL', 'Manual')], default='AUTOMATIC', max_length=10)),
                ('three_ds_status', models.CharField(choices=[('NOT_REQUIRED', 'Not required'), ('REQUIRED', 'Required'), ('AUTHENTICATED', 'Authenticated'), ('FAILED', 'Failed')], default='NOT_REQUIRED', max_length=16)),
                ('idempotency_key', models.CharField(blank=True, max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_intents', to='booking.booking')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, unique=True)),
                ('method', models.CharField(default='CARD', max_length=20)),
                ('provider', models.CharField(max_length=32)),
                ('provider_charge_id', models.CharField(max_length=128, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('AUTHORISED', 'Authorised'), ('CAPTURED', 'Captured'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('PARTIALLY_REFUNDED', 'Partially refunded')], max_length=20)),
                ('card_brand', models.CharField(blank=True, max_length=20)),
                ('card_last4', models.CharField(blank=True, max_length=4)),
                ('authorised_at', models.DateTimeField(blank=True, null=True)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('failure_code', models.CharField(blank=True, max_length=64)),
                ('failure_message', models.CharField(blank=True, max_length=255)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='booking.booking')),
                ('intent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.paymentintent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProviderWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=32)),
                ('provider_event_id', models.CharField(max_length=128, unique=True)),
                ('event_type', models.CharField(max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('signature_verified', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(condition=models.Q(('processed_at__isnull', True)), fields=['processed_at'], name='idx_webhook_pending')],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed')], default='REQUESTED', max_length=12)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('provider_refund_id', models.CharField(blank=True, max_length=128)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('refundable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_approved', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='booking.booking')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payments.payment')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_type', models.CharField(choices=[('SALE', 'Sale'), ('PAYMENT', 'Payment'), ('REFUND', 'Refund'), ('PENALTY', 'Penalty'), ('ADJUSTMENT', 'Adjustment')], max_length=12)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(blank=True, max_length=128)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='booking.booking')),
            ],
            options={
                'verbose_name_plural': 'ledger entries',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['booking', 'created_at'], name='idx_ledger_booking')],
            },
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['booking', '-created_at'], name='idx_intent_booking'),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['status', 'created_at'], name='idx_intent_pending'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['booking', '-created_at'], name='idx_payment_booking'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['status', '-created_at'], name='idx_refund_queue'),
        ),
    ]
