# Generated by Django 5.2.17 on 2026-09-02 04:34

import apps.common.uuid7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('booking', '0001_initial'),
        ('inventory', '0001_initial'),
        ('pricing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, unique=True)),
                ('pnr', models.CharField(max_length=6, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('HELD', 'Held'), ('PENDING_TICKETING', 'Pending ticketing'), ('TICKETED', 'Ticketed'), ('CONFIRMED', 'Confirmed'), ('CHANGE_PENDING', 'Change pending'), ('DISRUPTED', 'Disrupted'), ('REBOOKED', 'Rebooked'), ('CANCELLED', 'Cancelled'), ('REFUND_PENDING', 'Refund pending'), ('REFUNDED', 'Refunded'), ('EXPIRED', 'Expired')], default='DRAFT', max_length=20)),
                ('trip_type', models.CharField(choices=[('ONE_WAY', 'One way'), ('ROUND_TRIP', 'Round trip'), ('MULTI_CITY', 'Multi city')], default='ONE_WAY', max_length=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('base_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ancillary_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=32)),
                ('hold_expires_at', models.DateTimeField(blank=True, null=True)),
                ('booked_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=255)),
                ('source_channel', models.CharField(choices=[('WEB', 'Web'), ('AGENCY', 'Agency'), ('OPS', 'Ops')], default='WEB', max_length=10)),
                ('version', models.PositiveIntegerField(default=1)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='accounts.agency')),
                ('promo_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='pricing.promocode')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveSmallIntegerField()),
                ('cabin', models.CharField(choices=[('ECONOMY', 'Economy'), ('PREMIUM_ECONOMY', 'Premium economy'), ('BUSINESS', 'Business'), ('FIRST', 'First')], max_length=16)),
                ('rbd', models.CharField(max_length=1)),
                ('fare_basis', models.CharField(blank=True, max_length=16)),
                ('marketing_flight_number', models.CharField(max_length=8)),
                ('status', models.CharField(choices=[('HELD', 'Held'), ('CONFIRMED', 'Confirmed'), ('FLOWN', 'Flown'), ('CANCELLED', 'Cancelled')], default='HELD', max_length=12)),
                ('baggage_allowance', models.JSONField(blank=True, default=dict)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='booking.booking')),
                ('fare_family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_segments', to='pricing.farefamily')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_segments', to='inventory.flight')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='InventoryHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offer_id', models.UUIDField()),
                ('cabin', models.CharField(choices=[('ECONOMY', 'Economy'), ('PREMIUM_ECONOMY', 'Premium economy'), ('BUSINESS', 'Business'), ('FIRST', 'First')], max_length=16)),
                ('rbd', models.CharField(max_length=1)),
                ('seats', models.PositiveSmallIntegerField()),
                ('expires_at', models.DateTimeField()),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('hold_key', models.CharField(blank=True, max_length=64)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holds', to='booking.booking')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holds', to='inventory.flight')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('ADT', 'Adult'), ('CHD', 'Child'), ('INF', 'Infant')], max_length=3)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('X', 'Unspecified')], max_length=1)),
                ('nationality', models.CharField(blank=True, max_length=2)),
                ('doc_type', models.CharField(blank=True, choices=[('PASSPORT', 'Passport'), ('NATIONAL_ID', 'National ID'), ('DRIVING_LICENCE', 'Driving licence')], max_length=20)),
                ('doc_number', models.CharField(blank=True, max_length=64)),
                ('doc_expiry', models.DateField(blank=True, null=True)),
                ('frequent_flyer_number', models.CharField(blank=True, max_length=32)),
                ('associated_adult', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infants', to='booking.passenger')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='booking.booking')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['contact_email'], name='idx_booking_contact'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'hold_expires_at'], name='idx_booking_hold'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['-created_at'], name='idx_booking_recent'),
        ),
        migrations.AddIndex(
            model_name='bookingsegment',
            index=models.Index(fields=['flight'], name='idx_segment_flight'),
        ),
        migrations.AddConstraint(
            model_name='bookingsegment',
            constraint=models.UniqueConstraint(fields=('booking', 'sequence'), name='uniq_segment_sequence'),
        ),
        migrations.AddIndex(
            model_name='inventoryhold',
            index=models.Index(condition=models.Q(('released_at__isnull', True)), fields=['expires_at'], name='idx_hold_expiry'),
        ),
        migrations.AddIndex(
            model_name='passenger',
            index=models.Index(fields=['last_name'], name='idx_passenger_surname'),
        ),
    ]
