# Generated by Django 5.2.17 on 2026-09-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_bookingsegment_inventoryhold_passenger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='price_breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
